stages:
    - debug
    - release
    - deliver
    - trigger

debug:
    stage: debug
    script:
        - ./build debug
    except:
         - master

release:
    stage: release
    script:
        - ./build release
    except:
        - master

sample:
    stage: release 
    script:
        - ./build sample

delivery:
    stage: deliver
    variables:
        MIU_PATH: "/opt/staging/miu"
        INC_PATH: "$MIU_PATH/include"
        DBG_PATH: "$MIU_PATH/lib-dbg"
        REL_PATH: "$MIU_PATH/lib-rel"
        BIN_PATH: "$MIU_PATH/binaries"
        UT_PATH: "$MIU_PATH/unittest"
    script:
        - ./build debug
        - ./build release

        - mkdir -p $INC_PATH
        - rm -fr $INC_PATH/svc
        - cp -frv ./include/svc $INC_PATH

        - mkdir -p $DBG_PATH
        - cp -fv debug/libsvc.a $DBG_PATH
        - cp -fv debug/libmiu.so $DBG_PATH

        - mkdir -p $REL_PATH
        - cp -fv release/libsvc.a $REL_PATH
        - cp -fv release/libmiu.so $REL_PATH

        - mkdir -p $UT_PATH
        - cp -fv release/ut_svc $UT_PATH

    only:
        - master

ref:
    stage: trigger
    script:
        - curl -X POST -F token=6ca2fc03cb03064c8bb905dc10bd57 -F ref=master <url>/api/v4/projects/17/trigger/pipeline
    only:
        - master
